package com.xincode.app

import androidx.compose.runtime.Composable
import androidx.compose.ui.platform.LocalContext
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * 界面中英文Fs字典 v1。
 *
 * 用法: `Text(t("设置"))` —— 中文原文即 key,英文模式查表,查不到回退中文。
 * 带参数的用 `tx("删除「%s」及其所有记录？", title)`。
 * 读取 [XincodeApplication.appLanguage](mutableState),切换后引用处自动重组,秒切换。
 * 覆盖范围:侧边栏 / 聊天输入岛与抽屉 / 设置 / 终端 / 会话与项目列表 /
 * 供应商 / 用量 / 身份卡 / Skill-MCP 弹窗。深层页面后续补。
 */
object AppStrings {
    private val EN: Map<String, String> = mapOf(
        // —— 侧边栏 ——
        "像素指挥室" to "Control Room",
        "终端" to "Terminal",
        "群聊房间" to "Group Rooms",
        "设置" to "Settings",
        "重命名" to "Rename",
        "保存" to "Save",
        "取消" to "Cancel",
        "删除会话" to "Delete chat",
        "删除「%s」及其所有记录？" to "Delete \"%s\" and all its messages?",
        "新对话" to "New chat",
        "置顶会话" to "Pin chat",
        "取消置顶" to "Unpin",
        "删除" to "Delete",
        "置顶" to "Pinned",
        // —— 终端 ——
        "返回" to "Back",
        "终端 · Ubuntu" to "Terminal · Ubuntu",
        "终端 · root shell" to "Terminal · root shell",
        "清屏" to "Clear",
        "收藏当前" to "Save current",
        "已收藏到快捷指令栏" to "Saved to shortcuts",
        "该指令已在快捷列表中" to "Already in shortcuts",
        "请先在下方输入要收藏的命令" to "Enter a command below first",
        "输入命令，点击右侧运行" to "Type a command, then Run",
        "运行中…可直接输入回答进程提问（如 Y/N）" to "Running… type answers (Y/N) here",
        "运行" to "Run",
        "终止" to "Stop",
        "删除快捷指令" to "Delete shortcut",
        "确认从快捷栏移除指令「%s」？" to "Remove \"%s\" from shortcuts?",
        "当前通道不支持交互输入" to "Channel doesn't support interactive input",
        // —— 设置 ——
        "外观" to "Appearance",
        "账户与模型" to "Account & Models",
        "权限与安全" to "Permissions & Security",
        "数据" to "Data",
        "Agent工具" to "Agent Tools",
        "关于" to "About",
        "暗色模式" to "Dark mode",
        "近黑终端配色" to "Near-black terminal",
        "羊皮纸浅色配色" to "Parchment light",
        "回车发送" to "Enter to send",
        "回车直接发送(换行用输入法组合键)" to "Enter sends (newline via IME combo)",
        "回车换行(发送靠 [→] 键)" to "Enter inserts newline (send via [→])",
        "界面语言 / Language" to "Language / 语言",
        "当前：中文" to "Current: Chinese",
        "中文" to "Chinese",
        "搜索设置项…" to "Search settings…",
        "外观、模型、权限与 Agent 工具" to "Appearance, models, permissions & agent tools",
        "隐藏项设置" to "Hidden sections",
        "★ 我的置顶" to "★ My pins",
        "前往 ›" to "Open ›",
        "☆ 置顶常用功能：点击任意设置项右侧的 ☆ 即可置顶到此处" to "☆ Tap ☆ on any item to pin it here",
        "模型与供应商" to "Models & Providers",
        "管理 API 密钥、切换默认模型与探索供应商市场" to "Manage API keys, switch models, explore market",
        "个人昵称" to "Nickname",
        "显示在侧边栏头像与对话页，空=默认" to "Shown in sidebar avatar; empty = default",
        "请输入昵称（最多12字）" to "Enter nickname (max 12 chars)",
        "身份卡" to "Identity cards",
        "为不同场景配置独立助手" to "Configure assistants per scenario",
        "权限分级" to "Permission tiers",
        "查询" to "Check",
        "查询中…" to "Checking…",
        "请求授权" to "Authorize",
        "普通 · 沙盒运行" to "Normal · Sandboxed",
        "Root · 已授权" to "Root · Granted",
        "Shizuku · 已授权" to "Shizuku · Granted",
        "Shizuku · 未授权" to "Shizuku · Unauthorized",
        "Root 优先，终端与工具已接管" to "Root first, terminal & tools taken over",
        "Shizuku 接管终端，Root > Shizuku > 普通 自动降级" to "Shizuku terminal, auto fallback Root > Shizuku > Normal",
        "检测到 Shizuku，点击授权后可提升权限" to "Shizuku found, authorize to elevate",
        "分级：Root > Shizuku > 普通 · 终端已接管，自动降级执行" to "Tiers: Root > Shizuku > Normal · auto fallback",
        "Git/文件等基础能力可用，构建类需 Root/Shizuku" to "Git/files work; builds need Root/Shizuku",
        "● root 已授权" to "● Root granted",
        "○ root 未授权" to "○ Root denied",
        "✗ 无 root" to "✗ No root",
        "[!] 检测超时" to "[!] Detection timeout",
        "检测中…" to "Checking…",
        "运行诊断" to "Run diagnostics",
        "审计日志" to "Audit log",
        "查看所有调用记录" to "View all call records",
        "── Root 诊断报告 ──" to "── Root diagnostics ──",
        "结论: Root 正常工作" to "Result: Root works",
        "结论: Root 异常" to "Result: Root abnormal",
        "记忆与存储" to "Memory & Storage",
        "管理本地记忆数据" to "Manage local memory",
        "上下文压缩" to "Context compression",
        "自定义上下文长度、自动压缩阈值与总结规则" to "Context length, auto-compact rules",
        "精编记忆" to "Curated memory",
        "查看/编辑 agent 记住的你与近况" to "View/edit what the agent remembers",
        "定时任务" to "Scheduled tasks",
        "管理后台自动化 cron 任务" to "Manage background cron jobs",
        "Agent 工具" to "Agent tools",
        "全局工作区目录" to "Global workspace",
        "环境配置" to "Dev environments",
        "安装 Node/Python/uv/SSH/JDK/Gradle/Rust/Go 等开发环境" to "Install Node/Python/uv/SSH/JDK/Gradle/Rust/Go",
        "配置环境" to "Profiles",
        "多套独立配置(工作/私用各一套),可克隆与导出导入" to "Work/private profiles, clone & import/export",
        "功能模型配置" to "Feature models",
        "上下文总结/后台复盘/子智能体/Goal 裁判等各自指定模型" to "Per-feature models: summary, review, subagents, judge",
        "模型委托" to "Model delegation",
        "视觉/推理/翻译/转写各配一个副模型(另填 URL 与 Key)" to "Aux models for vision/reason/translate/transcribe",
        "子智能体" to "Subagents",
        "主脑指挥的专职子智能体(各管各的技能),可自建" to "Dedicated subagents, customizable",
        "局域网设备" to "LAN devices",
        "发现同一 Wi-Fi 下其它开着 XINCODE 的设备" to "Discover XINCODE devices on this Wi-Fi",
        "看板" to "Kanban",
        "跨会话的长期待办,可把 AI 的计划一键导入" to "Cross-session todos, import AI plans",
        "用量分析" to "Usage stats",
        "30 天趋势、模型分布、缓存命中率与成本估算" to "30-day trends, models, cache hits, cost",
        "日志" to "Logs",
        "崩溃与运行日志,按级别/关键词过滤,可复制反馈" to "Crash & runtime logs, filterable",
        "代码索引" to "Code index",
        "把工作区代码结构抽进本地索引,AI 查符号定义与调用关系不再靠读文件" to "Local symbol index for the workspace",
        "Git 接入" to "Git integration",
        "OAuth 登录 GitHub + 远程/本地 MCP(免 root 也能用)" to "GitHub OAuth + remote/local MCP",
        "搜索 API Key" to "Search API key",
        "未配置" to "Not configured",
        "输入 Tavily Search API Key" to "Enter Tavily Search API key",
        "关于 XINCODE" to "About XINCODE",
        "版本信息、检查更新、项目地址与开源许可" to "Version, updates, repo & licenses",
        "自定义隐藏设置项" to "Customize hidden sections",
        "隐藏不常用功能" to "Hide unused sections",
        "取消勾选的区块将不在设置主界面展示，随时可恢复：" to "Unchecked sections will be hidden; restore anytime:",
        "完成" to "Done",
        // —— 聊天 ——
        "Share" to "分享",
        "Rename" to "重命名",
        "Pin" to "固定",
        "Unpin" to "取消固定",
        "Delete" to "删除",
        "Low" to "低",
        "Medium" to "中",
        "High" to "高",
        "Extra" to "超高",
        "Max" to "最强",
        "Auto" to "自动",
        "On demand" to "按需",
        "Always available" to "始终可用",
        "Can't be changed for this chat" to "本会话不可更改",
        "模型按需自主调用工具" to "Tools auto-invoked by the model",
        "需要时加载，消息更多、精度稍低" to "Loaded on demand; more messages, lower accuracy",
        "启动即就绪，消息更少、精度更高" to "Ready from start; fewer messages, better accuracy",
        "访问权限" to "Access",
        "正常" to "Normal",
        "完全访问" to "Full access",
        "计划模式" to "Plan mode",
        "协同 · 完全访问" to "Collab · Full access",
        "协同 · 正常" to "Collab · Normal",
        "上下文用量" to "Context usage",
        "增强提示词" to "Enhance prompt",
        "优化当前输入" to "Polish current input",
        "目标模式" to "Goal mode",
        "前往 Goal 模式" to "Open Goal mode",
        "多Agent协同" to "Multi-agent collab",
        "已开启：主脑+子智能体并行" to "On: main + subagents in parallel",
        "已关闭" to "Off",
        "已选择" to "Selected",
        "输入消息与 AI 聊天" to "Chat with AI",
        "输入目标,让 XINCODE 自主完成…" to "Enter a goal for XINCODE…",
        "重命名会话" to "Rename chat",
        "插话给正在工作的 AI(不打断)…" to "Talk to the working AI (no interrupt)…",
        "Add to chat" to "Add to chat",
        "Camera" to "Camera",
        "Photos" to "Photos",
        "Files" to "Files",
        "Web search" to "Web search",
        "Memory" to "Memory",
        "Add to project" to "Add to project",
        "MCP" to "MCP",
        "Skills" to "Skills",
        "工具权限" to "Tool permissions",
        "连接本地或远程工具服务" to "Connect local or remote tool services",
        "已配置 %s 个服务" to "%s services configured",
        "将技能指令添加到输入框" to "Insert skill instructions into input",
        "已配置 %s 个技能" to "%s skills configured",
        "选择技能" to "Pick a skill",
        "暂无技能(可在 设置→Skills 管理)" to "No skills yet (manage in Settings → Skills)",
        "关闭" to "Close",
        "选择 MCP 服务器" to "Pick an MCP server",
        "暂无 MCP 服务器(点下方「管理」去添加)" to "No MCP servers (tap Manage below)",
        "MCP 服务器" to "MCP servers",
        "连接和管理外部工具" to "Connect & manage external tools",
        "添加" to "Add",
        "尚未添加 MCP 服务器" to "No MCP servers yet",
        "● 已连接" to "● Connected",
        "○ 未连接" to "○ Disconnected",
        "断开" to "Disconnect",
        "连接" to "Connect",
        "连接中..." to "Connecting…",
        "连接成功: %s (%s 个工具)" to "Connected: %s (%s tools)",
        "连接失败: %s" to "Failed: %s",
        "已断开: %s" to "Disconnected: %s",
        "已删除: %s" to "Deleted: %s",
        "添加 MCP 服务器" to "Add MCP server",
        "名称" to "Name",
        "示例: GitHub MCP" to "e.g. GitHub MCP",
        "Auth Header (可选)" to "Auth Header (optional)",
        "Skills 技能" to "Skills",
        "创建和管理可复用提示词模板" to "Create & manage reusable prompt templates",
        "还没有技能\n点右上角 + 创建一个" to "No skills yet\nTap + to create one",
        "内置" to "Built-in",
        "自建" to "Auto-made",
        "删除技能" to "Delete skill",
        "确定删除「%s」？此操作不可撤回。" to "Delete \"%s\"? This cannot be undone.",
        "新建技能" to "New skill",
        "编辑技能" to "Edit skill",
        "描述（可选）" to "Description (optional)",
        "内容（Markdown 指令，注入系统提示）" to "Content (Markdown, injected into system prompt)",
        "管理" to "Manage",
        "Select model" to "Select model",
        "Effort" to "Effort",
        "分享" to "Share",
        "固定" to "Pin",
        "加入项目" to "Add to project",
        "设为主页" to "Add to home",
        "分享对话" to "Share chat",
        "已复制" to "Copied",
        "复制消息" to "Copy message",
        "转发消息" to "Forward message",
        "更多消息操作" to "More actions",
        "重试" to "Retry",
        // —— 会话/项目列表 ——
        "Search Chats" to "Search Chats",
        "批量删除" to "Delete selected",
        "退出多选" to "Exit selection",
        "置顶筛选" to "Pinned only",
        "多选管理" to "Multi-select",
        "清除" to "Clear",
        "批量删除" to "Delete selected",
        "退出多选" to "Exit selection",
        "置顶筛选" to "Pinned only",
        "多选管理" to "Multi-select",
        "清除" to "Clear",
        "Search projects" to "Search projects",
        "返回项目列表" to "Back to projects",
        "更多操作" to "More actions",
        "Edit details" to "Edit details",
        "Private" to "Private",
        "Project knowledge" to "Project knowledge",
        "Add knowledge" to "Add knowledge",
        "Custom instructions" to "Custom instructions",
        "Add instructions" to "Add instructions",
        "What are you working on?" to "What are you working on?",
        "What are you trying to achieve?" to "What are you trying to achieve?",
        "New project" to "New project",
        "Project name" to "Project name",
        "Create" to "Create",
        "Open details" to "Open details",
        "No projects yet" to "No projects yet",
        "No matching projects" to "No matching projects",
        "Create a project to keep related chats and work together." to "Create a project to keep related chats and work together.",
        "Try a different project name." to "Try a different project name.",
        "项目操作" to "Project actions",
        "新建项目" to "New project",
        "搜索项目" to "Search projects",
        "No projects yet" to "No projects yet",
        "No matching projects" to "No matching projects",
        "New project" to "New project",
        "Project name" to "Project name",
        "Create" to "Create",
        "Cancel" to "Cancel",
        // —— 供应商 ——
        "模型与供应商" to "Models & Providers",
        "管理 API 密钥、运行模型与探索供应商市场" to "Manage keys, models and market",
        "供应商配置" to "Supplier configs",
        "管理 API、密钥和可用模型" to "Manage APIs, keys and models",
        "尚未添加任何供应商配置" to "No supplier configs yet",
        "支持 OpenAI、DeepSeek、Claude、通义千问及本地 Ollama 等接入" to "Supports OpenAI, DeepSeek, Claude, Qwen, local Ollama and more",
        "+ 立即添加配置" to "+ Add config now",
        "供应商" to "Supplier",
        "API 路径类型" to "API path type",
        "api_key" to "api_key",
        "启用模型（多选）" to "Enabled models (multi-select)",
        "+ 添加" to "+ Add",
        "加载中…" to "Loading…",
        "↻ 刷新" to "↻ Refresh",
        "模型能力" to "Model capabilities",
        "保存配置" to "Save config",
        "✓ 当前" to "✓ Active",
        "免费额度、订阅套餐和按量付费" to "Free tiers, plans and pay-as-you-go",
        "搜索供应商或模型" to "Search suppliers or models",
        "清除搜索" to "Clear search",
        "搜索供应商" to "Search suppliers",
        "筛选市场" to "Filter market",
        "筛选" to "Filter",
        "全部" to "All",
        "免费" to "Free",
        "套餐" to "Plan",
        "付费" to "Paid",
        "我的配置" to "My configs",
        "供应商市场" to "Supplier market",
        "已保存配置（%s）" to "%s saved configs",
        "点击条目即可直接切换为当前全局运行配置" to "Tap an entry to switch the global config",
        "+ 新建配置" to "+ New config",
        "尚未添加任何供应商配置" to "No supplier configs yet",
        "支持 OpenAI、DeepSeek、Claude、通义千问及本地 Ollama 等接入" to "Supports OpenAI, DeepSeek, Claude, Qwen, local Ollama and more",
        "+ 立即添加配置" to "+ Add config now",
        "名称" to "Name",
        "例如: 我的DeepSeek" to "e.g. MyDeepSeek",
        "供应商" to "Supplier",
        "拉取模型列表" to "Fetch models",
        "正在拉取…" to "Fetching…",
        "启用模型（多选）" to "Enabled models (multi-select)",
        "拉不到列表？直接填模型 ID，如 gpt-4o" to "No list? Type a model ID, e.g. gpt-4o",
        "+ 添加" to "+ Add",
        "模型能力" to "Model capabilities",
        "取消" to "Cancel",
        "保存配置" to "Save config",
        "✓ 配置已保存" to "✓ Config saved",
        "更换模型" to "Switch model",
        "配置模型" to "Configure model",
        // —— 用量 ——
        "用量分析" to "Usage stats",
        "7 天" to "7 days",
        "30 天" to "30 days",
        "60 天" to "60 days",
        "统计中…" to "Loading…",
        "输入" to "Input",
        "输出" to "Output",
        "调用次数" to "Calls",
        "缓存命中" to "Cache hits",
        "日均 token" to "Daily avg",
        "缓存读" to "Cache read",
        "每日 token(输入 + 输出)" to "Daily tokens (in + out)",
        "模型分布" to "Models",
        "成本估算" to "Cost estimate",
        "按 2026-01 各家官方价目(美元价×7.2,国产为人民币官价)粗算,仅供参考。未收录的模型不计入,实际以供应商账单为准。" to "Based on Jan-2026 official prices (USD×7.2). Unlisted models excluded; see your bill.",
        "估算(人民币)" to "Estimate (CNY)",
        "有价目数据 %s / %s 个模型" to "%s / %s models priced",
        // —— 身份卡 ——
        "身份卡" to "Identity cards",
        "为不同场景配置独立助手" to "Configure assistants per scenario",
        "新建" to "New",
        "重命名身份卡" to "Rename identity",
        "删除身份卡" to "Delete identity",
        "「%s」将被删除。已用过这张身份卡的 %s 个对话会失去关联,但对话内容不会丢失。" to "\"%s\" will be deleted. %s chats using it will be unlinked (contents kept).",
        "「%s」将被删除。" to "\"%s\" will be deleted.",
        "取消收藏" to "Unstar",
        "收藏" to "Star"
    )

    fun get(cn: String, lang: String): String =
        if (lang == "en") EN[cn] ?: cn else cn
}

/** 当前语言下的文案；读 appLanguage state，切换后自动重组秒切。 */
@Composable
fun t(cn: String): String {
    val app = LocalContext.current.applicationContext as XincodeApplication
    return AppStrings.get(cn, app.appLanguage)
}

/** 带参数的文案。 */
@Composable
fun tx(cn: String, vararg args: Any?): String {
    val s = t(cn)
    return try {
        String.format(s, *args)
    } catch (_: Exception) { s }
}

/** 会话日期：中文“2026年8月3日” / 英文“Aug 3, 2026”。 */
@Composable
fun chatDate(timestamp: Long): String {
    val app = LocalContext.current.applicationContext as XincodeApplication
    val d = Date(timestamp)
    return if (app.appLanguage == "en") {
        SimpleDateFormat("MMM d, yyyy", Locale.US).format(d)
    } else {
        SimpleDateFormat("yyyy年M月d日", Locale.CHINA).format(d)
    }
}
